language: node_js

node_js:
  - "stable"
  - "10"
  - "8"
  - "6"

script:
  - npm run lint
  # coveralls will run test:jest
  - npm run coveralls
  - npm run build

cache: npm

matrix:
  fast_finish: true
